[tool.poetry]
name = "projeto-django"
version = "0.1.0"
description = ""
authors = ["thiagoamorim11 <ttthiago.amorim@gmail>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
django = "^5.0.4"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
